import { Injectable, signal, computed, PLATFORM_ID, inject } from '@angular/core';
import { isPlatformBrowser } from '@angular/common';

export const translations = {
  en: {
    // Navigation / Header
    home: 'Home',
    products: 'Products',
    productsApi: 'ProductsAPI',
    about: 'About',
    contact: 'Contact',
    search: 'Search',
    register: 'Register',
    login: 'Login',
    profile: 'Profile',
    chat: 'Chat',
    logout: 'Logout',
    language: 'Language',
    becomeSeller: 'Become a Seller',
    createShopTitle: 'Become a Seller',
    createShopDesc: 'Register your shop information to start selling your handmade goods on Handora.',
    shopName: 'Shop Name',
    shopNamePlaceholder: 'Enter your unique shop name',
    shopDescriptionEn: 'Description (English)',
    shopDescriptionAr: 'Description (Arabic)',
    shopDescEnPlaceholder: 'Describe your shop in English...',
    shopDescArPlaceholder: 'Describe your shop in Arabic...',
    shopLogoHint: 'Allowed formats: JPG, PNG. Max size: 2MB.',
    registerShopBtn: 'Register Shop',
    registeringShop: 'Registering Shop...',
    shopNameRequired: 'Shop name is required.',
    writeShopReview: 'Write a Shop Review',
    updateShopReview: 'Update Your Review',
    deleteReviewBtn: 'Delete Review',
    deleteReviewConfirm: 'Are you sure you want to delete your review?',
    reviewPlaceholderShop: 'Tell us about your experience with this artisan shop...',
    onlyPurchasedCanReview: 'Only customers who have completed an order from this shop can leave a review.',
    noReviewsYetShop: 'No written reviews yet for this shop. Be the first to share your experience!',
    reviewSuccess: 'Review submitted successfully!',
    reviewDeleteSuccess: 'Review deleted successfully!',
    reviewsCountLabel: 'reviews',
    // Sidebar / Dashboard
    overview: 'Overview',
    myOrders: 'My Orders',
    myWishlist: 'My Wishlist',
    followedShops: 'Followed Shops',
    myReviews: 'My Reviews',
    editProfile: 'Edit Profile',
    signOut: 'Sign Out',
    welcomeBack: 'Welcome back',
    artisanSupporter: 'Artisan Supporter',
    memberSince: 'Member since',
    aboutMe: 'About Me',
    totalOrders: 'Total Orders',
    wishlistItems: 'Wishlist Items',
    shopsFollowed: 'Shops Followed',
    reviewsWritten: 'Reviews Written',
    recentFollows: 'Recent Follows',
    recentOrders: 'Recent Orders',
    viewAll: 'View All',
    unfollow: 'Unfollow',
    noOrdersYet: 'No orders placed yet',
    orderHistory: 'My Order History',
    trackReviewPurchase: 'Track and review details of all purchases you have made.',
    startShopping: 'Start Shopping',
    wishlistIsEmpty: 'Wishlist is Empty',
    exploreProducts: 'Explore Products',
    viewDetails: 'View Details',
    followedArtisans: 'Followed Artisans & Shops',
    noFollowedShops: 'No Followed Shops',
    discoverShops: 'Discover Shops',
    visitShop: 'Visit Shop',
    noReviewsYet: 'No Reviews Written Yet',
    productTitle: 'Product Title',
    orderDate: 'Order Date',
    itemsCount: 'Items Count',
    totalAmount: 'Total Amount',
    orderStatus: 'Order Status',
    paymentStatus: 'Payment Status',
    actions: 'Actions',
    details: 'Details',
    // Edit Profile
    backToDashboard: 'Back to Dashboard',
    saveChanges: 'Save Changes',
    savingChanges: 'Saving Changes...',
    cancel: 'Cancel',
    fullName: 'Full Name',
    phoneNumber: 'Phone Number',
    bioDescription: 'Bio / Short description',
    allowedFormats: 'Allowed formats: JPG, PNG. Max size: 2MB.',
    // Statuses
    pending: 'Pending',
    confirmed: 'Confirmed',
    processing: 'Processing',
    shipped: 'Shipped',
    delivered: 'Delivered',
    cancelled: 'Cancelled',
    refunded: 'Refunded',
    paid: 'Paid',
    failed: 'Failed',
    // Added Keys for Dashboard & Edit Profile
    updateProfileDesc: 'Update your personal details and custom avatar',
    fullNamePlaceholder: 'Enter your full name',
    phonePlaceholder: 'Enter your phone number (optional)',
    bioPlaceholder: 'Tell us about yourself, your passion for crafts, or what you look for in artisans...',
    item: 'item',
    items: 'items',
    orderId: 'Order ID',
    noComment: 'No comment provided.',
    bannerDesc: 'Your space to track your artisan experiences, orders, and favorite shops.',
    noRecentFollows: 'Not following any shops yet',
    noOrdersDesc: "You haven't placed any orders on Handora. Explore our unique collections of handmade items!",
    wishlistDesc: 'Keep track of the unique items you love.',
    wishlistEmptyDesc: 'Save your favorite handmade products here by clicking the heart icon on search or product details pages.',
    followedArtisansDesc: 'Artisans whose craft you love. Be notified about their new collections!',
    noFollowedShopsDesc: 'Follow artisan shops to support their craft and easily find them later.',
    verifiedArtisan: 'Verified Artisan',
    reviewsDesc: 'Feedback you have shared about products purchased.',
    noReviewsDesc: 'Share your thoughts! After receiving an order, you can review items to help other buyers and support sellers.',

    // Home Page Keys
    welcomeToHandora: 'Welcome to Handoura',
    discoverUniqueProducts: 'Discover unique handmade products made with love in Egypt',
    shopNow: 'Shop Now 🛍️',
    hideClock: '🙈 Hide Clock',
    showClock: '🕐 Show Clock',
    searchProducts: '🔍 Search Products',
    searchPlaceholder: 'Search by product name...',
    showingResultsFor: 'Showing results for',
    searching: 'Searching...',

    // About Page Keys
    aboutHandmadeHub: 'ℹ️ About HandmadeHub',
    storyAndMission: 'Our story and mission',
    ourMission: '🎯 Our Mission',
    missionText: 'We connect talented Egyptian artisans with customers who appreciate the beauty and value of handmade products.',
    whoWeAre: '🌍 Who We Are',
    whoWeAreText: 'Founded in Cairo, HandmadeHub is a platform dedicated to preserving traditional crafts while bringing them to modern customers.',
    ourBranches: '📍 Our Branches',
    cairoMainBranch: '🏙️ Cairo — Main Branch',
    alexandria: '🌊 Alexandria',
    aswan: '☀️ Aswan',
    ourStory: '📖 Our Story',
    ourStoryText: 'Handora started with a simple belief: that every handmade piece carries the soul of its creator. We set out to give Egyptian artisans a digital home where they can showcase their heritage to the world.',

    // Contact Page Keys
    contactUs: '📞 Contact Us',
    contactSubtitle: "We'd love to hear from you!",
    emailLabel: '📧 Email:',
    phoneLabel: '📱 Phone:',
    addressLabel: '📍 Address:',
    cairoEgypt: 'Cairo, Egypt',
    contactFormTitle: 'Send us a Message',
    subjectLabel: 'Subject',
    messageLabel: 'Message',
    messagePlaceholder: 'Write your message here...',
    sendMessageBtn: 'Send Message ✉️',
    sendingMessage: 'Sending...',
    messageSentSuccess: 'Thank you! Your message has been sent successfully.',

    // Not Found Page Keys
    pageNotFound: 'Oops! Page not found.',
    goHome: '🏠 Go Home',

    // Products Page Keys
    ownerLabel: 'Owner:',
    allCategories: 'All Categories',
    outOfStock: 'Out of Stock',
    lastOneItem: 'Last One Item!',
    lastTwoItems: 'Last Two Items!',
    inStock: 'In Stock',
    quantityLabel: 'Quantity:',
    unavailable: 'Unavailable',
    buy: 'Buy',
    noProductsFound: 'No products found!',
    loadingProducts: 'Loading products...',
    failedToLoadProducts: 'Failed to load products',

    // Product Detail Page Keys
    productNotFound: 'Product not found!',
    ownProductNotice: 'This is your product.',
    ownShopNotice: 'This is your shop.',
    noProductsAvailable: 'No products available',
    reviewsLabel: 'Reviews',
    backToProducts: 'Back to Products',
    productIdLabel: 'Product ID',
    pieces: 'pieces',
    categoryIdLabel: 'Category ID',
    buyNow: 'Buy Now',
    back: 'Back',

    // Wishlist Page Keys
    loadingWishlist: 'Loading wishlist...',
    addToCart: 'Add to Cart',
    wishlistIsEmptyTitle: 'Your wishlist is empty',
    wishlistEmptyText: 'Save your favorite handmade items here and come back to them anytime.',
    browseProducts: 'Browse Products',
    yourSavedPieces: 'YOUR SAVED PIECES',
    discoverMoreHandmade: 'Discover more handmade pieces',
    browse: 'Browse',
    adding: 'Adding...',
    egp: 'EGP',
    failedLoadWishlist: 'Failed to load wishlist.',
    failedRemoveItem: 'Failed to remove item.',

    // Cart Page Keys
    shoppingCart: 'Shopping Cart',
    subtotal: 'Subtotal',
    shipping: 'Shipping',
    calculatedAtCheckout: 'Calculated at checkout',
    estimatedTotal: 'Estimated Total',
    proceedToCheckout: 'Proceed to Checkout',
    continueShopping: 'Continue Shopping',
    secureCheckout: 'Secure Checkout',
    cartIsEmpty: 'Your cart is empty',
    cartIsEmptyDesc: 'Looks like you haven\'t added anything yet. Browse our handmade collection and find something special.',
    loadTestProducts: '🛒 Load Test Products',
    loadingCart: 'Loading cart...',
    totalLabel: 'Total',

    // Checkout Page Keys
    backToCart: 'Back to Cart',
    shippingAddress: 'Shipping Address',
    firstName: 'First Name',
    lastName: 'Last Name',
    street: 'Street',
    city: 'City',
    country: 'Country',
    deliveryMethod: 'Delivery Method',
    loadingDeliveryOptions: 'Loading delivery options...',
    couponOptional: 'Coupon (Optional)',
    orderNotesOptional: 'Order Notes (Optional)',
    placingOrder: 'Placing Order...',
    placeOrder: 'Place Order',
    summary: 'Summary',
    checkoutSummaryNote: 'Items in your cart will be calculated when you place the order.',
    editCart: 'Edit Cart',

    // Orders & Payments Page Keys
    cartLabel: 'Cart',
    loadingOrders: 'Loading orders...',
    noOrdersYetTitle: 'No orders yet',
    noOrdersYetDesc: 'Start shopping and your orders will appear here.',
    itemLabel: 'item(s)',
    backToOrders: 'Back to Orders',
    loadingOrderDetails: 'Loading order details...',
    order: 'Order',
    buyer: 'Buyer',
    notes: 'Notes:',
    couponApplied: 'Coupon applied:',
    priceLabel: 'Price',
    qtyLabel: 'Qty',
    delivery: 'Delivery',
    completePayment: 'Complete Payment',
    securePaymentPaymob: 'Secure payment via Paymob',
    preparingPaymentGateway: 'Preparing payment gateway...',
    backToOrder: 'Back to Order',
    securedByPaymob: 'Secured by Paymob',
    processingPaymentDoNotReload: 'Processing payment... Please do not reload the page.',
    waitingPaymentConfirmation: 'Waiting for payment confirmation...',
    paymentSuccessful: 'Payment Successful!',
    orderConfirmedProcessed: 'Your order has been confirmed and is being processed.',
    viewOrder: 'View Order',
    somethingWentWrongTryAgain: 'Something went wrong. Please try again.',
    tryAgain: 'Try Again',

    // Chat Page Keys
    handoraDirectMessages: 'Handora Direct Messages',
    selectChatPartner: 'Select a buyer or seller from the sidebar list to start chatting in real-time.',
    conversationsTitle: 'Conversations',
    searchChatPlaceholder: 'Search buyers & sellers...',
    noConversationsFound: 'No conversations found',
    noMessagesYet: 'No messages yet. Send a message to start the conversation!',
    uploadingPhoto: 'Uploading photo...',
    typeAMessage: 'Type a message...',

    // Seller Dashboard Keys
    sellerDashboard: 'Seller Dashboard',
    earnings: 'Earnings',
    followers: 'Followers',
    customRequests: 'Custom Requests',
    settings: 'Settings',
    myProducts: 'My Products',
    addProduct: 'Add Product',
    editProduct: 'Edit Product',
    storeOverview: 'Store Overview',
    revenue: 'Revenue',
    activeCustomers: 'Active Customers',
    salesCount: 'Sales Count',
    analytics: 'Analytics',
    productName: 'Product Name',
    category: 'Category',
    stock: 'Stock',
    price: 'Price',
    description: 'Description',
    saveProduct: 'Save Product',
    payoutAccounts: 'Payout Accounts',
    paymentGateway: 'Payment Gateway',
    bankTransfer: 'Bank Transfer',
    // New keys for Chat & Shop
    seller: 'Seller',
    noMessages: 'No messages yet',
    photoAttachment: '📷 Photo',
    yesterday: 'Yesterday',
    attachPhoto: 'Attach photo',
    removeAttachment: 'Remove attachment',
    closeFullscreen: 'Close fullscreen view',
    imageUploadFailed: 'Image upload failed. Please try again.',
    loadingShop: 'Loading shop...',
    failedToLoadShop: 'Failed to load shop',
    cannotSendToSelf: 'You cannot send messages to yourself.',
    phoneNotAllowed: 'Phone numbers are not allowed in chat.',
    linksNotAllowed: 'Links are not allowed in chat.',
    artisan: 'Artisan',
    following: 'Following',
    followShop: 'Follow Shop',
    rating: 'Rating',
    status: 'Status',
    owner: 'Owner',
    verified: 'Verified',
    unverified: 'Unverified',
    allCreations: 'All Creations',
    reviews: 'Reviews',
    orderSummary: 'Order Summary',
    noProductsYetShop: 'No products yet.',
    featuredPiece: 'Featured Piece',
    defaultShopDesc: 'A unique handmade shop crafted with love and intention.',
    viewDetail: 'View Detail',
    sale: 'Sale',
    loadMoreCreations: 'Load More Creations',
    aboutShop: 'About',
    noDescriptionYet: 'No description provided yet.',
    reviewsComingSoon: 'Reviews coming soon.',
    freeShipping: 'Free Shipping',
    // Auth Pages Keys
    craftedConnections: 'Handora:<br>Crafted Connections.<br>Handmade Mastery.',
    creatorsCollectors: 'Join our community of creators and collectors.',
    welcomeBackSanctuary: 'Please sign in to your artisan sanctuary.',
    emailAddress: 'Email Address',
    passwordLabel: 'Password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot Password?',
    signIn: 'Sign In',
    welcomeBackTitle: 'Welcome Back.',
    newToHandora: 'New to Handora?',
    createAccount: 'Create an account',
    joinHandoraTitle: 'Join Handora. Shape Your Story.',
    addPhoto: 'add photo',
    artisanPortrait: 'Your Artisan Portrait',
    optionalLabel: '(Optional)',
    artisanBiography: 'Your Artisan Biography',
    tellYourStoryPlaceholder: 'Tell your story...',
    nameLabel: 'Name',
    nameRequired: 'Name is required.',
    emailRequired: 'Email is required.',
    validEmail: 'Please enter a valid email.',
    passwordsDoNotMatch: 'Passwords do not match.',
    passwordRequired: 'Password is required.',
    passwordMinLength: 'Password must be at least 8 characters.',
    passwordPattern: 'Password must contain letters and numbers.',
    confirmPasswordLabel: 'Confirm Password',
    alreadyMember: 'Already a member?',
    joinHandoraBtn: 'Join Handora',
    verifyEmailTitle: 'Verify Your Email.',
    codeSentMsg: 'We sent a 6-digit code to',
    otpCodeLabel: 'OTP Code',
    otpPlaceholder: 'Enter 6-digit code',
    verifyBtn: 'Verify',
    resendCode: 'Resend Code',
    resendCodeIn: 'Resend code in',
    forgotPasswordTitle: 'Forgot Password',
    forgotPasswordInstructions: 'Enter your email address to receive a password reset link.',
    sendResetLink: 'Send Reset Link',
    backToLogin: 'Back to Login',
    resetPasswordTitle: 'Reset Password',
    resetPasswordBtn: 'Reset Password',
    newPassword: 'New Password',
    resetToken: 'Reset Token',
    continueWithGoogle: 'Continue with Google',

    // Extended localization
    shopByCraft: 'Shop by Craft',
    viewAllCrafts: 'View All Crafts',
    artisans: 'Artisans',
    allProducts: 'All Products',
    startSelling: 'Start Selling',
    myAccount: 'My Account',
    giftFinder: 'Gift Finder',
    searchPlaceholderHeader: 'Search products, artisans, crafts...',
    heroBeadsTag: 'HANDMADE BEADS',
    heroBeadsTitle: 'Wear Your',
    heroBeadsTitleL2: 'Story',
    heroBeadsSubtitle: 'Every bead carries a soul. Discover handcrafted jewelry made with passion by Egyptian artisans.',
    heroBeadsBtn: 'Explore Beads',
    heroBeadsWatermark: 'BEADS',
    heroPotteryTag: 'HANDMADE POTTERY',
    heroPotteryTitle: 'Shaped by',
    heroPotteryTitleL2: 'Ancient Hands',
    heroPotterySubtitle: 'Clay transformed into art. Each piece tells the story of Egypt\'s timeless heritage.',
    heroPotteryBtn: 'Explore Pottery',
    heroPotteryWatermark: 'POTTERY',
    heroCrochetTag: 'HANDMADE CROCHET',
    heroCrochetTitle: 'Crafted with',
    heroCrochetTitleL2: 'Love & Thread',
    heroCrochetSubtitle: 'One stitch at a time. Unique crochet pieces woven with creativity and warmth.',
    heroCrochetBtn: 'Explore Crochet',
    heroCrochetWatermark: 'CROCHET',
    shopByCategory: 'Shop by Category',
    categorySubtitle: 'Discover the finest handmade crafts made with love and skill by Egypt\'s finest artisans',
    comingSoon: 'Coming Soon',
    productsCountLabel: 'Products',
    shopOurBestsellers: 'Shop Our Bestsellers',
    shopAll: 'SHOP ALL',
    percentOff: 'OFF',
    compare: 'Compare',
    addToCartCaps: 'ADD TO CART',
    topShops: 'Top Shops',
    highlyRecommended: 'HIGHLY RECOMMENDED',
    discoverMore: 'DISCOVER MORE',
    verifiedBuyer: 'Verified Buyer',
    whyChooseHandaura: 'Why Choose Handaura',
    valuesSubtitle: 'The story behind every handmade piece',
    valueTitleLove: 'Handcrafted with Love',
    valueDescLove: 'Every piece tells a story — made by skilled Egyptian hands.',
    valueTitleSust: 'Natural & Sustainable',
    valueDescSust: 'From Nile clay to palm leaves — honoring the earth in every creation.',
    valueTitleEmpower: 'Empowering Artisans',
    valueDescEmpower: 'Your purchase supports real people and keeps ancient traditions alive.',
    play: 'PLAY',
    joinMailingList: 'JOIN OUR MAILING LIST',
    getDiscountCodeText: 'Get $20 discount for your first order',
    emailPlaceholderSubscribe: 'Your email address...',
    subscribeBtn: 'SUBSCRIBE',
    sendingBtn: 'SENDING...',
    subscribedBtn: 'SUBSCRIBED!',
    onlineOnlyDisclaimer: '*Online only. First-time subscribers only',
    subscribeSuccessMsg: 'Thank you! Check your inbox for your $20 discount code.',
    infoColTitle: 'INFORMATION',
    offers: 'Offers',
    palmWeaving: 'Palm Weaving',
    footerDesc: 'We provide the finest handmade crafts crafted with love by Egypt\'s most skilled artisans. Every piece tells a story you can treasure.',
    copyrightText: 'All rights reserved',
    bestSellers: 'Best Sellers',
    categoriesTitle: 'CATEGORIES',
    pottery: 'Pottery',
    beads: 'Beads',
    crochet: 'Crochet',
    macrame: 'Macrame',
    embroidery: 'Embroidery',
    candles: 'Candles',
    leatherCraft: 'Leather Craft',
    getInTouch: 'GET IN TOUCH',
    phoneAbbr: 'T:',
    emailAbbr: 'E:',
    brandName: 'Handaura',
    shop: 'Shop',
    heroPassionTag: 'HANDMADE WITH PASSION',
    heroPassionTitle: 'Where Every Piece',
    heroPassionTitleL2: 'Tells a Story',
    heroPassionSubtitle: 'Every piece carries the touch of skilled hands and a unique story. Discover handmade treasures crafted by Egyptian artisans with passion and love.',
    heroPassionBtn: 'EXPLORE HANDAURA',
    heroPassionWatermark: 'HANDAURA',
    heroCustomTag: 'YOUR VISION, THEIR CRAFT',
    heroCustomTitle: 'Have Something',
    heroCustomTitleL2: 'Special in Mind?',
    heroCustomSubtitle: 'Share your dream with our artisans and watch it come to life. From personalized engravings to bespoke designs, every custom piece is crafted with passion and precision.',
    heroCustomBtn: 'REQUEST CUSTOM PIECE',
    heroCustomWatermark: 'CUSTOM',
    heroGiftsTag: 'GIFTS WITH SOUL',
    heroGiftsTitle: 'Find the Perfect Gift',
    heroGiftsTitleL2: 'For Every Moment',
    heroGiftsSubtitle: 'Whether it\'s a birthday, anniversary, or just because — discover handmade treasures matched to your occasion and your loved one\'s unique spirit.',
    heroGiftsBtn: 'DISCOVER GIFTS',
    heroGiftsWatermark: 'GIFTS',
    heroCustomDesign: 'Custom Design',
    heroBirthday: 'Birthday',
    heroAnniversary: 'Anniversary',
    heroWedding: 'Wedding',
    heroMothersDay: "Mother's Day",
    heroJustBecause: 'Just Because',
    minQtyReached: 'Minimum quantity reached',
    maxQtyReached: 'Maximum available quantity reached',
    soldOutTooltip: 'Product is currently unavailable'
  },
  ar: {
    // Navigation / Header
    home: 'الرئيسية',
    products: 'المنتجات',
    productsApi: 'واجهة المنتجات',
    about: 'من نحن',
    contact: 'اتصل بنا',
    search: 'البحث',
    register: 'تسجيل جديد',
    login: 'تسجيل الدخول',
    profile: 'الملف الشخصي',
    chat: 'المحادثة',
    logout: 'تسجيل الخروج',
    language: 'اللغة',
    becomeSeller: 'كن بائعاً',
    createShopTitle: 'كن بائعاً على هاندورا',
    createShopDesc: 'سجّل معلومات متجرك للبدء في بيع منتجاتك اليدوية على هاندورا.',
    shopName: 'اسم المتجر',
    shopNamePlaceholder: 'أدخل اسم متجرك المميز',
    shopDescriptionEn: 'الوصف (بالأرقام الإنجليزية)',
    shopDescriptionAr: 'الوصف (بالعربية)',
    shopDescEnPlaceholder: 'اكتب وصفاً لمتجرك بالإنجليزية...',
    shopDescArPlaceholder: 'اكتب وصفاً لمتجرك بالعربية...',
    shopLogoHint: 'الصيغ المسموح بها: JPG، PNG. الحجم الأقصى: 2 ميجابايت.',
    registerShopBtn: 'تسجيل المتجر',
    registeringShop: 'جاري تسجيل المتجر...',
    shopNameRequired: 'اسم المتجر مطلوب.',
    writeShopReview: 'اكتب تقييمك للمتجر',
    updateShopReview: 'تحديث تقييمك',
    deleteReviewBtn: 'حذف التقييم',
    deleteReviewConfirm: 'هل أنت متأكد من رغبتك في حذف هذا التقييم؟',
    reviewPlaceholderShop: 'اكتب تجربتك مع متجر هذا الحرفي بالتفصيل...',
    onlyPurchasedCanReview: 'فقط العملاء الذين قاموا بإكمال طلب من هذا المتجر يمكنهم كتابة تقييم.',
    noReviewsYetShop: 'لا توجد مراجعات مكتوبة بعد لهذا المتجر. كن أول من يشارك تجربته!',
    reviewSuccess: 'تم تقديم التقييم بنجاح!',
    reviewDeleteSuccess: 'تم حذف التقييم بنجاح!',
    reviewsCountLabel: 'تقييمات',
    // Sidebar / Dashboard
    overview: 'لوحة التحكم',
    myOrders: 'طلباتي',
    myWishlist: 'قائمة الأمنيات',
    followedShops: 'المتاجر المتابعة',
    myReviews: 'تقييماتي',
    editProfile: 'تعديل الملف',
    signOut: 'تسجيل الخروج',
    welcomeBack: 'مرحباً بعودتك',
    artisanSupporter: 'داعم الحرفيين',
    memberSince: 'عضو منذ',
    aboutMe: 'نبذة عني',
    totalOrders: 'إجمالي الطلبات',
    wishlistItems: 'عناصر الأمنيات',
    shopsFollowed: 'المتاجر المتابعة',
    reviewsWritten: 'التقييمات المكتوبة',
    recentFollows: 'متابعات حديثة',
    recentOrders: 'أحدث الطلبات',
    viewAll: 'عرض الكل',
    unfollow: 'إلغاء المتابعة',
    noOrdersYet: 'لا توجد طلبات بعد',
    orderHistory: 'سجل طلباتي',
    trackReviewPurchase: 'تتبع وتفاصيل جميع المشتريات التي قمت بها.',
    startShopping: 'ابدأ التسوق',
    wishlistIsEmpty: 'قائمة الأمنيات فارغة',
    exploreProducts: 'اكتشف المنتجات',
    viewDetails: 'عرض التفاصيل',
    followedArtisans: 'الحرفيون والمتاجر المتابعة',
    noFollowedShops: 'لا توجد متاجر متابعة',
    discoverShops: 'اكتشف المتاجر',
    visitShop: 'زيارة المتجر',
    noReviewsYet: 'لا توجد تقييمات مكتوبة بعد',
    productTitle: 'عنوان المنتج',
    orderDate: 'تاريخ الطلب',
    itemsCount: 'عدد العناصر',
    totalAmount: 'المبلغ الإجمالي',
    orderStatus: 'حالة الطلب',
    paymentStatus: 'حالة الدفع',
    actions: 'الإجراءات',
    details: 'تفاصيل',
    // Edit Profile
    backToDashboard: 'العودة للوحة التحكم',
    saveChanges: 'حفظ التغييرات',
    savingChanges: 'جاري الحفظ...',
    cancel: 'إلغاء',
    fullName: 'الاسم الكامل',
    phoneNumber: 'رقم الهاتف',
    bioDescription: 'نبذة شخصية / وصف قصير',
    allowedFormats: 'الصيغ المسموح بها: JPG، PNG. الحجم الأقصى: 2 ميجابايت.',
    // Statuses
    pending: 'قيد الانتظار',
    confirmed: 'تم التأكيد',
    processing: 'قيد المعالجة',
    shipped: 'تم الشحن',
    delivered: 'تم التوصيل',
    cancelled: 'تم الإلغاء',
    refunded: 'تم الاسترجاع',
    paid: 'تم الدفع',
    failed: 'فشل',
    // Added Keys for Dashboard & Edit Profile
    updateProfileDesc: 'قم بتحديث تفاصيلك الشخصية والصورة الرمزية الخاصة بك',
    fullNamePlaceholder: 'أدخل اسمك الكامل',
    phonePlaceholder: 'أدخل رقم هاتفك (اختياري)',
    bioPlaceholder: 'أخبرنا عن نفسك، شغفك بالحرف اليدوية، أو ما تبحث عنه في الحرفيين...',
    item: 'عنصر',
    items: 'عناصر',
    orderId: 'رقم الطلب',
    noComment: 'لا يوجد تعليق.',
    bannerDesc: 'مساحتك الخاصة لتتبع تجاربك الحرفية، طلباتك، ومتاجر المتابعة الخاصة بك.',
    noRecentFollows: 'لا تتابع أي متاجر حالياً',
    noOrdersDesc: 'لم تقم بإجراء أي طلبات على هاندورا بعد. استكشف مجموعاتنا الفريدة من المنتجات المصنوعة يدوياً!',
    wishlistDesc: 'تتبع المنتجات الفريدة التي تحبها.',
    wishlistEmptyDesc: 'احفظ منتجاتك اليدوية المفضلة هنا بالضغط على أيقونة القلب في صفحات البحث أو تفاصيل المنتج.',
    followedArtisansDesc: 'الحرفيون والمتاجر الذين تحب أعمالهم. سيتم إخطارك بمجموعاتهم الجديدة!',
    noFollowedShopsDesc: 'تابع متاجر الحرفيين لدعم أعمالهم والوصول إليها بسهولة لاحقاً.',
    verifiedArtisan: 'حرفي موثق',
    reviewsDesc: 'الآراء والتقييمات التي شاركتها حول المنتجات التي قمت بشرائها.',
    noReviewsDesc: 'شاركنا برأيك! بعد استلام طلبك، يمكنك مراجعة وتقييم المنتجات لمساعدة المشترين الآخرين ودعم البائعين.',

    // Home Page Keys
    welcomeToHandora: 'مرحباً بكم في هاندورا',
    discoverUniqueProducts: 'اكتشف منتجات يدوية فريدة صنعت بكل حب في مصر',
    shopNow: 'تسوق الآن 🛍️',
    hideClock: 'Hide Clock 🙈',
    showClock: 'Show Clock 🕐',
    searchProducts: 'البحث عن المنتجات 🔍',
    searchPlaceholder: 'ابحث باسم المنتج...',
    showingResultsFor: 'عرض نتائج لـ',
    searching: 'جاري البحث...',

    // About Page Keys
    aboutHandmadeHub: 'عن هاندورا هوب ℹ️',
    storyAndMission: 'قصتنا ورسالتنا',
    ourMission: 'رسالتنا 🎯',
    missionText: 'نحن نربط الحرفيين المصريين الموهوبين بالعملاء الذين يقدرون جمال وقيمة المنتجات المصنوعة يدوياً.',
    whoWeAre: 'من نحن 🌍',
    whoWeAreText: 'تأسست هاندورا هوب في القاهرة، وهي منصة مخصصة للحفاظ على الحرف التقليدية وتقديمها للعملاء العصريين.',
    ourBranches: 'فروعنا 📍',
    cairoMainBranch: '🏙️ القاهرة — الفرع الرئيسي',
    alexandria: 'Alexandria 🌊',
    aswan: 'Aswan ☀️',
    ourStory: '📖 قصتنا',
    ourStoryText: 'بدأت هاندورا بإيمان بسيط: أن كل قطعة مصنوعة يدويًا تحمل روح صانعها. لقد شرعنا في منح الحرفيين المصريين موطنًا رقميًا حيث يمكنهم عرض تراثهم للعالم.',

    // Contact Page Keys
    contactUs: 'اتصل بنا 📞',
    contactSubtitle: 'يسعدنا دائماً تواصلك معنا!',
    emailLabel: '📧 البريد الإلكتروني:',
    phoneLabel: '📱 الهاتف:',
    addressLabel: '📍 العنوان:',
    cairoEgypt: 'القاهرة، مصر',
    contactFormTitle: 'أرسل لنا رسالة',
    subjectLabel: 'الموضوع',
    messageLabel: 'الرسالة',
    messagePlaceholder: 'اكتب رسالتك هنا...',
    sendMessageBtn: 'إرسال الرسالة ✉️',
    sendingMessage: 'جاري الإرسال...',
    messageSentSuccess: 'شكراً لك! تم إرسال رسالتك بنجاح.',

    // Not Found Page Keys
    pageNotFound: 'عذراً! الصفحة غير موجودة.',
    goHome: 'العودة للرئيسية 🏠',

    // Products Page Keys
    ownerLabel: 'المالك:',
    allCategories: 'جميع الفئات',
    outOfStock: 'غير متوفر',
    lastOneItem: 'آخر قطعة متوفرة!',
    lastTwoItems: 'آخر قطعتين متوفرتين!',
    inStock: 'متوفر',
    quantityLabel: 'الكمية:',
    unavailable: 'غير متوفر',
    buy: 'شراء',
    noProductsFound: 'لم يتم العثور على منتجات!',
    loadingProducts: 'جاري تحميل المنتجات...',
    failedToLoadProducts: 'فشل تحميل المنتجات',

    // Product Detail Page Keys
    productNotFound: 'المنتج غير موجود!',
    ownProductNotice: 'هذا المنتج الخاص بك.',
    ownShopNotice: 'هذا المتجر الخاص بك.',
    noProductsAvailable: 'لا توجد منتجات متوفرة',
    reviewsLabel: 'التقييمات',
    backToProducts: 'العودة للمنتجات',
    productIdLabel: 'رقم المنتج',
    pieces: 'قطع',
    categoryIdLabel: 'رقم الفئة',
    buyNow: 'شراء الآن',
    back: 'تراجع',

    // Wishlist Page Keys
    loadingWishlist: 'جاري تحميل قائمة الأمنيات...',
    addToCart: 'أضف إلى السلة',
    wishlistIsEmptyTitle: 'قائمة أمنياتك فارغة',
    wishlistEmptyText: 'احفظ منتجاتك اليدوية المفضلة هنا للعودة إليها في أي وقت.',
    browseProducts: 'تصفح المنتجات',
    yourSavedPieces: 'قطعك المحفوظة',
    discoverMoreHandmade: 'اكتشف المزيد من القطع اليدوية',
    browse: 'تصفح',
    adding: 'جاري الإضافة...',
    egp: 'ج.م',
    failedLoadWishlist: 'فشل تحميل قائمة الأمنيات.',
    failedRemoveItem: 'فشل إزالة العنصر.',

    // Cart Page Keys
    shoppingCart: 'سلة التسوق',
    subtotal: 'المجموع الفرعي',
    shipping: 'الشحن',
    calculatedAtCheckout: 'يتم احتسابه عند الدفع',
    estimatedTotal: 'المجموع التقديري',
    proceedToCheckout: 'المتابعة لإتمام الشحن',
    continueShopping: 'مواصلة التسوق',
    secureCheckout: 'دفع آمن ومحمي',
    cartIsEmpty: 'سلة تسوقك فارغة',
    cartIsEmptyDesc: 'يبدو أنك لم تقم بإضافة أي شيء بعد. تصفح مجموعتنا المميزة واعثر على شيء فريد.',
    loadTestProducts: 'تحميل منتجات تجريبية 🛒',
    loadingCart: 'جاري تحميل السلة...',
    totalLabel: 'الإجمالي',

    // Checkout Page Keys
    backToCart: 'العودة إلى السلة',
    shippingAddress: 'عنوان الشحن',
    firstName: 'الاسم الأول',
    lastName: 'اسم العائلة',
    street: 'الشارع',
    city: 'المدينة',
    country: 'البلد',
    deliveryMethod: 'طريقة التوصيل',
    loadingDeliveryOptions: 'جاري تحميل خيارات التوصيل...',
    couponOptional: 'كوبون الخصم (اختياري)',
    orderNotesOptional: 'ملاحظات الطلب (اختياري)',
    placingOrder: 'جاري تقديم الطلب...',
    placeOrder: 'تأكيد الطلب',
    summary: 'الملخص',
    checkoutSummaryNote: 'سيتم احتساب قيمة المنتجات وتكاليف الشحن عند تأكيد الطلب.',
    editCart: 'تعديل السلة',

    // Orders & Payments Page Keys
    cartLabel: 'السلة',
    loadingOrders: 'جاري تحميل الطلبات...',
    noOrdersYetTitle: 'لا توجد طلبات بعد',
    noOrdersYetDesc: 'ابدأ التسوق وسيتم عرض طلباتك هنا.',
    itemLabel: 'عناصر',
    backToOrders: 'العودة للطلبات',
    loadingOrderDetails: 'جاري تحميل تفاصيل الطلب...',
    order: 'الطلب',
    buyer: 'المشتري',
    notes: 'ملاحظات:',
    couponApplied: 'الكوبون المطبق:',
    priceLabel: 'السعر',
    qtyLabel: 'الكمية',
    delivery: 'التوصيل',
    completePayment: 'إتمام عملية الدفع',
    securePaymentPaymob: 'دفع آمن بواسطة Paymob',
    preparingPaymentGateway: 'جاري تجهيز بوابة الدفع...',
    backToOrder: 'العودة للطلب',
    securedByPaymob: 'مؤمن بواسطة Paymob',
    processingPaymentDoNotReload: 'جاري معالجة الدفع... يرجى عدم إعادة تحميل الصفحة.',
    waitingPaymentConfirmation: 'بانتظار تأكيد الدفع...',
    paymentSuccessful: 'تم الدفع بنجاح!',
    orderConfirmedProcessed: 'تم تأكيد طلبك وجاري العمل على معالجته وشحنه.',
    viewOrder: 'عرض الطلب',
    somethingWentWrongTryAgain: 'حدث خطأ ما. يرجى المحاولة مرة أخرى.',
    tryAgain: 'حاول مجدداً',

    // Chat Page Keys
    handoraDirectMessages: 'رسائل هاندورا المباشرة',
    selectChatPartner: 'اختر مشترياً أو بائعاً من القائمة الجانبية لبدء المحادثة الفورية.',
    conversationsTitle: 'المحادثات',
    searchChatPlaceholder: 'البحث عن المشترين والبائعين...',
    noConversationsFound: 'لم يتم العثور على محادثات',
    noMessagesYet: 'لا توجد رسائل بعد. أرسل رسالة لبدء المحادثة!',
    uploadingPhoto: 'جاري تحميل الصورة...',
    typeAMessage: 'اكتب رسالتك هنا...',

    // Seller Dashboard Keys
    sellerDashboard: 'لوحة تحكم البائع',
    earnings: 'الأرباح',
    followers: 'المتابعون',
    customRequests: 'الطلبات الخاصة',
    settings: 'الإعدادات',
    myProducts: 'منتجاتي',
    addProduct: 'إضافة منتج',
    editProduct: 'تعديل المنتج',
    storeOverview: 'نظرة عامة على المتجر',
    revenue: 'الإيرادات',
    activeCustomers: 'العملاء النشطون',
    salesCount: 'عدد المبيعات',
    analytics: 'التحليلات',
    productName: 'اسم المنتج',
    category: 'الفئة',
    stock: 'المخزون',
    price: 'السعر',
    description: 'الوصف',
    saveProduct: 'حفظ المنتج',
    payoutAccounts: 'حسابات الدفع',
    paymentGateway: 'بوابة الدفع',
    bankTransfer: 'تحويل بنكي',
    // New keys for Chat & Shop
    seller: 'بائع',
    noMessages: 'لا توجد رسائل بعد',
    photoAttachment: '📷 صورة',
    yesterday: 'أمس',
    attachPhoto: 'إرفاق صورة',
    removeAttachment: 'إزالة المرفق',
    closeFullscreen: 'إغلاق ملء الشاشة',
    imageUploadFailed: 'فشل تحميل الصورة. يرجى المحاولة مرة أخرى.',
    loadingShop: 'جاري تحميل المتجر...',
    failedToLoadShop: 'فشل تحميل المتجر',
    cannotSendToSelf: 'لا يمكنك إرسال رسائل إلى نفسك.',
    phoneNotAllowed: 'غير مسموح بمشاركة أرقام الهواتف في المحادثة.',
    linksNotAllowed: 'غير مسموح بمشاركة الروابط في المحادثة.',
    artisan: 'حرفي',
    following: 'متابع',
    followShop: 'متابعة المتجر',
    rating: 'التقييم',
    status: 'الحالة',
    owner: 'المالك',
    verified: 'موثق',
    unverified: 'غير موثق',
    allCreations: 'كل الإبداعات',
    reviews: 'التقييمات',
    orderSummary: 'ملخص الطلب',
    noProductsYetShop: 'لا توجد منتجات بعد.',
    featuredPiece: 'قطعة مميزة',
    defaultShopDesc: 'متجر منتجات يدوية فريدة صنعت بكل حب وإتقان.',
    viewDetail: 'عرض التفاصيل',
    sale: 'تخفيض',
    loadMoreCreations: 'تحميل المزيد من الإبداعات',
    aboutShop: 'عن',
    noDescriptionYet: 'لم يتم تقديم وصف بعد.',
    reviewsComingSoon: 'التقييمات قريباً.',
    freeShipping: 'شحن مجاني',
    // Auth Pages Keys
    craftedConnections: 'هاندورا:<br>اتصالات مصنوعة بحب.<br>إتقان الأعمال اليدوية.',
    creatorsCollectors: 'انضم إلى مجتمعنا من المبدعين ومحبي الفنون اليدوية.',
    welcomeBackSanctuary: 'يرجى تسجيل الدخول إلى محرابك الحرفي.',
    emailAddress: 'البريد الإلكتروني',
    passwordLabel: 'كلمة المرور',
    rememberMe: 'تذكرني',
    forgotPassword: 'هل نسيت كلمة المرور؟',
    signIn: 'تسجيل الدخول',
    welcomeBackTitle: 'مرحباً بعودتك.',
    newToHandora: 'جديد على هاندورا؟',
    createAccount: 'إنشاء حساب',
    joinHandoraTitle: 'انضم إلى هاندورا. ارسم قصتك.',
    addPhoto: 'إضافة صورة',
    artisanPortrait: 'صورتك الحرفية',
    optionalLabel: '(اختياري)',
    artisanBiography: 'سيرتك الحرفية',
    tellYourStoryPlaceholder: 'أدخل قصة نجاحك وشغفك...',
    nameLabel: 'الاسم',
    nameRequired: 'الاسم مطلوب.',
    emailRequired: 'البريد الإلكتروني مطلوب.',
    validEmail: 'يرجى إدخال بريد إلكتروني صالح.',
    passwordsDoNotMatch: 'كلمات المرور غير متطابقة.',
    passwordRequired: 'كلمة المرور مطلوبة.',
    passwordMinLength: 'يجب أن تتكون كلمة المرور من 8 أحرف على الأقل.',
    passwordPattern: 'يجب أن تحتوي كلمة المرور على حروف وأرقام.',
    confirmPasswordLabel: 'تأكيد كلمة المرور',
    alreadyMember: 'هل أنت عضو بالفعل؟',
    joinHandoraBtn: 'الانضمام لهاندورا',
    verifyEmailTitle: 'تأكيد بريدك الإلكتروني.',
    codeSentMsg: 'لقد أرسلنا رمزاً مكوناً من 6 أرقام إلى',
    otpCodeLabel: 'رمز التحقق',
    otpPlaceholder: 'أدخل الرمز المكون من 6 أرقام',
    verifyBtn: 'تحقق',
    resendCode: 'إعادة إرسال الرمز',
    resendCodeIn: 'إعادة إرسال الرمز خلال',
    forgotPasswordTitle: 'نسيت كلمة المرور',
    forgotPasswordInstructions: 'أدخل بريدك الإلكتروني لتلقي رابط إعادة تعيين كلمة المرور.',
    sendResetLink: 'إرسال رابط تعيين كلمة المرور',
    backToLogin: 'العودة لتسجيل الدخول',
    resetPasswordTitle: 'إعادة تعيين كلمة المرور',
    resetPasswordBtn: 'إعادة تعيين كلمة المرور',
    newPassword: 'كلمة المرور الجديدة',
    resetToken: 'رمز إعادة التعيين',
    continueWithGoogle: 'متابعة باستخدام Google',

    // Extended localization
    shopByCraft: 'تسوق حسب الحرفة',
    viewAllCrafts: 'عرض كل الحرف',
    artisans: 'حرفيّونا',
    allProducts: 'جميع المنتجات',
    startSelling: 'ابدأ البيع',
    myAccount: 'حسابي',
    giftFinder: 'مكتشف الهدايا',
    searchPlaceholderHeader: 'ابحث عن منتجات، حرفيين، مشغولات...',
    heroBeadsTag: 'خرز يدوي فريد',
    heroBeadsTitle: 'ارتدِ',
    heroBeadsTitleL2: 'قصتك',
    heroBeadsSubtitle: 'كل خرزة تحمل روحاً. اكتشف المجوهرات المصنوعة يدوياً بشغف بأيدي حرفيين مصريين.',
    heroBeadsBtn: 'اكتشف الخرز',
    heroBeadsWatermark: 'خرز',
    heroPotteryTag: 'فخار مصنوع يدوياً',
    heroPotteryTitle: 'تشكّل بأيدي',
    heroPotteryTitleL2: 'الأجداد',
    heroPotterySubtitle: 'الصلصال يتحول إلى فن. كل قطعة تحكي قصة التراث المصري الخالد.',
    heroPotteryBtn: 'اكتشف الفخار',
    heroPotteryWatermark: 'فخار',
    heroCrochetTag: 'كروشيه يدوي',
    heroCrochetTitle: 'صنع بكل',
    heroCrochetTitleL2: 'حب وخيط',
    heroCrochetSubtitle: 'غرزة تلو الأخرى. قطع كروشيه فريدة منسوجة بالإبداع والدفء.',
    heroCrochetBtn: 'اكتشف الكروشيه',
    heroCrochetWatermark: 'كروشيه',
    shopByCategory: 'تسوق حسب الفئة',
    categorySubtitle: 'اكتشف أرقى الحرف اليدوية المصنوعة بكل حب ومهارة بأيدي أفضل الحرفيين في مصر',
    comingSoon: 'قريباً',
    productsCountLabel: 'منتجات',
    shopOurBestsellers: 'تسوق الأكثر مبيعاً',
    shopAll: 'تسوق الكل',
    percentOff: 'خصم',
    compare: 'مقارنة',
    addToCartCaps: 'أضف إلى السلة',
    topShops: 'أفضل المتاجر',
    highlyRecommended: 'موصى به بشدة',
    discoverMore: 'اكتشف المزيد',
    verifiedBuyer: 'مشتري موثق',
    whyChooseHandaura: 'لماذا تختار هاندورا',
    valuesSubtitle: 'القصة وراء كل قطعة مصنوعة يدوياً',
    valueTitleLove: 'صنع بكل حب',
    valueDescLove: 'كل قطعة تحكي قصة — صنعت بأيدي مصرية ماهرة.',
    valueTitleSust: 'طبيعي ومستدام',
    valueDescSust: 'من طمي النيل إلى سعف النخيل — نحترم الأرض في كل إبداع.',
    valueTitleEmpower: 'تمكين الحرفيين',
    valueDescEmpower: 'شراؤك يدعم أشخاصًا حقيقيين ويحافظ على التقاليد القديمة حية.',
    play: 'تشغيل',
    joinMailingList: 'انضم إلى قائمتنا البريدية',
    getDiscountCodeText: 'احصل على خصم بقيمة 20 دولاراً لطلبك الأول',
    emailPlaceholderSubscribe: 'عنوان بريدك الإلكتروني...',
    subscribeBtn: 'اشتراك',
    sendingBtn: 'جاري الإرسال...',
    subscribedBtn: 'تم الاشتراك!',
    onlineOnlyDisclaimer: '*عبر الإنترنت فقط. للمشتركين لأول مرة فقط',
    subscribeSuccessMsg: 'شكراً لك! تحقق من بريدك الوارد للحصول على رمز الخصم بقيمة 20 دولاراً.',
    infoColTitle: 'معلومات',
    offers: 'العروض',
    palmWeaving: 'خوص النخيل',
    footerDesc: 'نقدم أرقى المشغولات اليدوية المصنوعة بكل حب بأيدي أمهر الحرفيين المصريين. كل قطعة تحكي قصة تعتز بها.',
    copyrightText: 'جميع الحقوق محفوظة',
    bestSellers: 'الأكثر مبيعاً',
    categoriesTitle: 'الفئات',
    pottery: 'فخار',
    beads: 'خرز',
    crochet: 'كروشيه',
    macrame: 'مكرامية',
    embroidery: 'تطريز',
    candles: 'شموع',
    leatherCraft: 'مشغولات جلدية',
    getInTouch: 'تواصل معنا',
    phoneAbbr: 'ت:',
    emailAbbr: 'ب:',
    brandName: 'هاندورا',
    shop: 'تسوق',
    heroPassionTag: 'صنع بكل شغف',
    heroPassionTitle: 'حيث كل قطعة',
    heroPassionTitleL2: 'تحكي قصة',
    heroPassionSubtitle: 'كل قطعة تحمل لمسة أيدٍ ماهرة وقصة فريدة. اكتشف كنوزاً يدوية صنعتها أيدي حرفيين مصريين بكل شغف وحب.',
    heroPassionBtn: 'اكتشف هاندورا',
    heroPassionWatermark: 'هاندورا',
    heroCustomTag: 'رؤيتك، وحرفيتهم',
    heroCustomTitle: 'هل تفكر في شيء',
    heroCustomTitleL2: 'خاص ومميز؟',
    heroCustomSubtitle: 'شارك حلمك مع حرفيينا وشاهده وهو ينبض بالحياة. من النقوش المخصصة إلى التصاميم الفريدة، كل قطعة تصنع خصيصاً لك بشغف وإتقان.',
    heroCustomBtn: 'طلب قطعة مخصصة',
    heroCustomWatermark: 'مخصص',
    heroGiftsTag: 'هدايا تحمل روحاً',
    heroGiftsTitle: 'اعثر على الهدية المثالية',
    heroGiftsTitleL2: 'لكل مناسبة',
    heroGiftsSubtitle: 'سواء كان عيد ميلاد، ذكرى سنوية، أو بدون مناسبة — اكتشف كنوزاً يدوية تناسب مناسبتك وروح من تحب.',
    heroGiftsBtn: 'اكتشف الهدايا',
    heroGiftsWatermark: 'هدايا',
    heroCustomDesign: 'تصميم مخصص',
    heroBirthday: 'عيد ميلاد',
    heroAnniversary: 'ذكرى سنوية',
    heroWedding: 'زفاف',
    heroMothersDay: 'عيد الأم',
    heroJustBecause: 'بدون مناسبة',
    minQtyReached: 'تم الوصول إلى الحد الأدنى للكمية',
    maxQtyReached: 'تم الوصول إلى الحد الأقصى للكمية المتاحة',
    soldOutTooltip: 'المنتج غير متوفر حالياً'
  }
};;

@Injectable({
  providedIn: 'root'
})
export class LanguageService {
  private platformId = inject(PLATFORM_ID);
  
  // Active language signal
  currentLang = signal<'en' | 'ar'>('en');

  constructor() {
    if (isPlatformBrowser(this.platformId)) {
      const savedLang = localStorage.getItem('lang') as 'en' | 'ar';
      if (savedLang === 'en' || savedLang === 'ar') {
        this.setLanguage(savedLang);
      } else {
        this.updateDocumentDirection('en');
      }
    }
  }

  setLanguage(lang: 'en' | 'ar'): void {
    this.currentLang.set(lang);
    if (isPlatformBrowser(this.platformId)) {
      localStorage.setItem('lang', lang);
      this.updateDocumentDirection(lang);
    }
  }

  toggleLanguage(): void {
    const nextLang = this.currentLang() === 'en' ? 'ar' : 'en';
    this.setLanguage(nextLang);
  }

  private updateDocumentDirection(lang: 'en' | 'ar'): void {
    if (typeof document !== 'undefined') {
      const html = document.documentElement;
      html.setAttribute('lang', lang);
      html.setAttribute('dir', lang === 'ar' ? 'rtl' : 'ltr');
    }
  }

  // Helper translation computed function
  translate(key: keyof typeof translations.en): string {
    const lang = this.currentLang();
    return translations[lang][key] || translations['en'][key] || (key as string);
  }
}
